# Configuration file for Faster RCNN

####################
# Common params    #
####################
label_map: './cargan/detector/label_maps/kitti.pbtxt'

#######################
# Inference Parameters#
#######################
interference:
  server:          localhost:9000
  frame_width:     360
  frame_height:    320
  score_threshold: 0.2
  frame_fps:       60


#########################
# Deployment Parameters #
#########################
deploy_params:
  output_path:      /tmp/     # it will generate a directory using model[name] (/tmp/yolov2_darknet)
  version:          1         # a TF Serving may have multiple versions
  maximum_boxes:    100
  iou_threshold:    0.5
  score_threshold:  0.0

